### ISSUE TITLE
无法启动，需要什么什么吗

### ISSUE THREAD

**Issue by zcracker** [BCYDTZ/luci-app-UUGameAcc#3]
![image](https://user-images.githubusercontent.com/9046704/125222878-655b0800-e2fd-11eb-9fc3-e734b1a8b534.png)
无法启动，需要什么什么吗

**Comment by BCYDTZ** [comment]
什么架构的？

**Comment by zcracker** [comment]
arm  ipq4019

**Comment by BCYDTZ** [comment]
> arm ipq4019

你重新拉取代码试试？

**Comment by BCYDTZ** [comment]
> arm ipq4019

目前手机没有arm的路由器，不知道有没有效果。。。。
